# Generated by Django 5.1 on 2024-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_set_question_quiz_delete_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
