# Generated by Django 5.1 on 2024-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_option_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
